### PR TITLE
Document `mult`

### PR DESCRIPTION
**Pull request by Rufflewind**
This is based on my reading of the quaternion implementation.  If this is correct, is there perhaps a cleaner way to express this?

### CODE REVIEW

**Comment by phadej** [comment]
Shouldn't you comment / document the particular instance, not the class? i.e. https://github.com/ekmett/algebra/blob/0e04c01f11960a842c66f86f6cbdb27f7a2d12b5/src/Numeric/Algebra/Quaternion.hs#L161 here if I follow the code?

**Comment by ekmett** [comment]
This isn't a general law for `mult`, just for many instances.

**Comment by Rufflewind** [comment]
Then what is the correct interpretation of `mult`?

**Comment by ekmett** [comment]
The notion in question is that of an [algebra over a field](https://en.wikipedia.org/wiki/Algebra_over_a_field).

Every vector space is a free vector space. In `linear` and `algebra`, I represent them by using a representable functor with an appropriate basis. Something like `R2 a` is isomorphic to `(Bool -> a)` where `Bool` is the representation of R2. `Algebra` goes one step further from this notion and equips my vector space with a bilinear product.

e.g. We can view complex numbers as a vector space over the reals, but we can _also_ multiply complex numbers.

Instead of denoting this by as a function from `(f a, f a) -> f a` which may appear more obvious, the solution taken here is to re-arrange things so that it is a function that collapses a vector space with representation (x, x) into a vector space with representation x. `((x, x) -> a) -> x -> a` but I uncurry the first argument to get `(x -> x -> a) -> x -> a`. 

In this representation most of the math for the properties of such a bilinear form follows automatically.

**Comment by Rufflewind** [comment]
> Shouldn't you comment / document the particular instance, not the class?

I was trying to come up with a more general interpretation.

> In this representation most of the math for the properties of such a bilinear form follows automatically.

OK, that helped clear things up.  Maybe that should be added to the docs?

I still think interpreting them as structure constants is useful since that establishes a link between the your abstract definition of an algebra vs the more traditional presentation, even if it's not fully general.

---

Let me see if I can elaborate this a bit.  The structure constants `c` are defined by the relationship:

~~~hs
i × j = ∑[c i j k ⋅ k | k ← x]
~~~

where `i` and `j` are basis vectors and `x` is the basis.  In Haskell, I would perhaps render this as:

~~~hs
mult' (delta (i, j)) == \ k -> c i j k
~~~

where for convenience I defined

~~~hs
mult' :: ((x, x) -> a) -> x -> a
mult' f k = mult (uncurry f) k

-- | Kronecker delta
delta :: x -> x -> a
delta e e'
  | e == e'   = one
  | otherwise = zero
~~~

From here, the bilinear product `(×)` is given by (this might be useful to include in the documentation too):

~~~hs
v1 × v2 = mult' (v1 ⊗ v2)
~~~

where `(⊗)` is the outer product:

~~~hs
(⊗) :: (x -> a) -> (x -> a) -> ((x, x) -> a)
v1 ⊗ v2 = \ (i, j) -> v1 i * v2 j
~~~

To ensure bilinearity, I figure `mult'` has to be linear too (right?):

~~~hs
mult' ((+) <$> v1 <*> v2) == (+) <$> mult' v1 <*> mult' v2
mult' ((s *) <$> v) == (s *) <$> mult' v
~~~

Now suppose I apply `mult` to some arbitrary vector `f`, which I decompose into some linear combination of the basis elements:

~~~hs
f = ∑[f i j ⋅ i × j | i ← x, j ← x]
~~~

This should always be possible (by virtue of being a basis).  Translating this into Haskell:

~~~hs
f == \ i' j' -> sum [f i j * delta (i, j) (i', j') | i <- x, j <- x]
  == liftedSum [(f i j *) <$> delta (i, j) | i <- x, j <- x]
  where liftedSum = foldr (liftA2 (+)) (pure zero)
~~~

If I use the linearity laws for `mult'`, then I get:

~~~hs
mult' f
  == mult' (liftedSum [(f i j *) <$> delta (i, j) | i <- x, j <- x])
  == liftedSum [(f i j *) <$> mult' (delta (i, j)) | i <- x, j <- x]
  == liftedSum [(f i j *) <$> (\ k -> c i j k) | i <- x, j <- x]
  == \ k -> sum [f i j * c i j k | i <- x, j <- x]
~~~

I did assume here that `a` is `Unital`, and that `x` could be enumerated, but I don't think I made any big leaps of faith here did I?

**Comment by ekmett** [comment]
It is a good starting intuition for the enumerable cases, but x really
doesn't have to be enumerable.

That sum can be much less well defined than the actual cases that arise in
practice. Nothing requires us to be able to draw from x or that the sums be
finite. You can get this in many ways, e.g. using your notation, by c i j k
being very sparse and knowing the shape of that pattern rather than
enumerating all of x and summing over the result, etc.

x can be a vector space in its own right. (y -> r) -> r with a constraint
that the outer function is linear is a way to model covectors for instance.
The things we can do with this Cont like monad are quite handy. All the
monad combinators, etc. correspond to doing things like currying/tensoring
vector spaces, etc.

**Pull request closed without merging**
