### PR TITLE
Allow containers-0.6

### LINKED ISSUE #20: Allow containers 0.6
It would be nice if algebra were updated to require containers <0.7 instead of <0.6. It seems to compile correctly with the new version of containers.

### PR DESCRIPTION
**Pull request by Bodigrim**
Closes #20.

### CODE REVIEW

**Comment by Bodigrim** [comment]
(GHC 8.2.1 build fails with `ghc: panic! (the 'impossible' happened)`, but GHC 8.2.2 is fine)

Ping @konn @ekmett

**Comment by cartazio** [comment]
Weird. Is this a bug in semigroupids? @ryanglscott

**Comment by cartazio** [comment]
Oh if 8.2.2 is fine but .1 isn’t sounds like a ghc bug

**Comment by RyanGlScott** [comment]
That panic is a manifestation of [GHC#14051](https://gitlab.haskell.org/ghc/ghc/issues/14051), an old GHC bug that was exclusive to 8.2.1.

**Pull request merged**
